emgage/engage-ui

src/components/ClickableChip/tests/ClickableChip.test.tsx

Created pull request for Clickable choice component.

features/30342-ClickableChip-UnitTest. 

---

src/components/Card/tests/Card.test.tsx
src/components/Chip/tests/Chip.test.tsx
src/components/DisplayText/tests/DisplayText.test.tsx
src/components/FormLayout/tests/FormLayout.test.tsx
src/components/Label/tests/Label.test.tsx
src/components/Loading/tests/Loading.test.tsx
src/components/Scrollable/tests/Scrollable.test.tsx
src/components/Select/tests/Select.test.tsx
src/components/Stack/tests/Stack.test.tsx
src/components/Subheading/tests/Subheading.test.tsx
src/components/TextField/tests/TextField.test.tsx
src/components/Tooltip/tests/Tooltip.test.tsx

We resolve all the unit test issues except mentioned in US#30680 - Resolve failed Unit Tests for existing Components.

Resolve failing unit tests in master branch.

---

src/components/ValidatedForm/tests/ValidatedForm.test.tsx

- Unit tests for ValidatedForm Component.

ValidatedForm Unit Tests

---

docs/src/styles/components-page.scss
docs/src/styles/global-styles.scss
docs/src/styles/nav.scss

1)Remove some unnecessary pre-included styles 
2)Added some styles for fix component large size/zooming issues.
2)Minor css change for fix sidebar issue
Thanks,
Sapan

#32747 comment: Fix Documentation Styles (remove pre-included styles)

---

src/components/Popover/Popover.tsx

Popover fix

---

src/components/Drawer/Drawer.tsx

Revert "Z-index changes in Drawer"

---

example/src/App.tsx
src/components/Select/Select.scss
src/components/Select/Select.tsx
src/components/TextField/TextField.scss
src/components/TextField/TextField.tsx
themes/Delicious/Select.scss
themes/Delicious/TextField.scss

Added "loading" prop to Select component and necessary code/styling. Updating TextField "loading" prop code to support inclusion of placeholder text and made some additional styling fixes.

fix: id:39721 adding loading state to Select and fixes for TextField

---

example/src/App.tsx
src/components/Badge/Badge.scss
src/components/Badge/Badge.tsx
src/components/BreadCrumb/BreadCrumb.tsx
src/components/Icon/Icon.scss
src/components/Icon/Icon.tsx
src/components/Table/TableHead.tsx
src/styles/foundation/colors.scss

Made the color palette and badge component updates for 39744.

fix: id:39744 color palette and badge component updates

---

src/components/TreeView/TreeView.scss

```
JisonLexerError: Lexical error on line 1: Unrecognized text.`
Erroneous area:
1: 100% - 0.7em - (14/16)em
^........................^
```

Fix bug with postcss, make style rule simpler

---

src/components/ComboBox/ComboBox.scss
src/components/Popover/PopoverOverlay.tsx

Bug fixing for popover overlaping with header and laguage icon overlapping with sticky footer

fix: 44330, 44023: Popover Z-index, language icon overlap fix

---

example/src/App.tsx
src/components/Grid/Grid.scss
src/components/Grid/Grid.tsx
src/components/Grid/GridContent.tsx
src/components/Grid/index.ts
src/components/index.ts

Grid styling with different styling method

fix: 44692 Grid UI component styling

---

src/components/Heading/Heading.scss
src/components/Heading/Heading.tsx
src/components/MultipleCheckboxFacets/MultipleCheckboxFacets.scss
src/components/MultipleCheckboxFacets/MultipleCheckboxFacets.tsx
src/styles/foundation/typography.scss
src/styles/shared/typography.scss

UI - Create/Update Audience - Faceted Query Styling

fix: id:44714 style add/update audience screen

---

src/components/Table/Table.scss

table data was overlapping in add field in field template

fix: id:44818 table data was overlaping in add field in field template

---

src/components/Select/Select.tsx

This PR resolved [43739](https://atera.tpondemand.com/RestUI/Board.aspx#page=board/4941726065867675222&appConfig=eyJhY2lkIjoiOTEwQzZFODEyODVCQ0Y4MTg5RUIyMEJEQTVDMEM2OUYifQ==&boardPopup=userstory/43739/silent).

Feature/43739: code refactoring to use modern seed response

---

src/components/Picker/Picker.tsx

https://atera.tpondemand.com/entity/44550-fe-group-add-member-greater-member
bug fixed

fix: 44550 Group AddMember member not displayed in dropdown bug fixed

---

src/components/Sticky/Sticky.scss
src/components/Sticky/Sticky.tsx

Add Members Picker suggestions dropdown behind footer

fix: id:41061 Add Members Picker suggestions dropdown behind footer

---

docs/src/examples/StickyExample/StickyExample.tsx
docs/src/examples/StickyExample/StickyExample1.tsx
example/src/App.tsx
src/components/Picker/Picker.scss
src/components/Sticky/tests/Sticky.test.tsx

sticky props are missing in other relate files

fix: id:41061 issue resolved after passing props in sticky

---

src/components/Card/Card.tsx
src/components/Card/CardBody.tsx
src/components/Card/CardFooter.tsx
src/components/Card/CardHeader.tsx
src/components/Card/CardSection.tsx
src/components/Card/Context.ts

https://atera.tpondemand.com/entity/45514-fe-handle-event-bubbling-for-card

feat: 45514 Handle event bubbling in Card component and children

---

src/components/Sticky/Sticky.scss

issue resolve when footerAuto class apply

fix: id:41061 issue resolve when footerAuto class apply

---

src/components/Grid/Grid.scss

FE - Create ContentStore: Blank space is shown & it shows 3 contentdef in a row instead of 4 in step-1 Select Content Template

fix: create contentStore: blank space is shown & it shows 3

---

src/components/TextField/TextField.scss

https://atera.tpondemand.com/entity/45236-fe-simpleshort-text-primitive-widget-suffix

fix: 45236 TextField suffix overlapped on scrollbar fixed

---

themes/Delicious/TextField.scss

https://atera.tpondemand.com/entity/45238-fe-shortsimple-text-primitive-widget-entered

fix: 45238 TextField prefix/suffix not aligned with input text fixed

---

src/components/TextField/TextField.tsx
themes/Delicious/Labelled.scss

https://atera.tpondemand.com/entity/45237-fe-shortsimple-text-primitive-widget-prefix

fix: 45237 TextField prefix is overlapped on label fixed

---

src/components/TreeView/TreeNode.tsx
src/components/TreeView/TreeView.tsx

This PR resolved [45909](https://atera.tpondemand.com/RestUI/Board.aspx#page=board/4941726065867675222&appConfig=eyJhY2lkIjoiOTEwQzZFODEyODVCQ0Y4MTg5RUIyMEJEQTVDMEM2OUYifQ==&boardPopup=bug/45909/silent).

Bugfix/45909: appDefList moreAction is not working

---

src/components/Table/Table.tsx

This PR resolved [45107](https://atera.tpondemand.com/RestUI/Board.aspx#page=board/4941726065867675222&appConfig=eyJhY2lkIjoiOTEwQzZFODEyODVCQ0Y4MTg5RUIyMEJEQTVDMEM2OUYifQ==&boardPopup=bug/45107/silent).

Bugfix/45107: create ContentStore issue

---

example/src/App.tsx
src/components/RangeSlider/RangeSlider.tsx
src/components/RangeSlider/components/DualThumb/DualThumb.scss
src/components/RangeSlider/components/DualThumb/DualThumb.tsx
src/components/RangeSlider/components/DualThumb/EventListener.tsx
src/components/RangeSlider/components/DualThumb/RangeSlider.scss
src/components/RangeSlider/components/DualThumb/features/index.ts
src/components/RangeSlider/components/DualThumb/index.ts
src/components/RangeSlider/components/InlineError/InlineError.scss
src/components/RangeSlider/components/InlineError/InlineError.tsx
src/components/RangeSlider/components/InlineError/index.ts
src/components/RangeSlider/components/Labelled.tsx
src/components/RangeSlider/components/SingleThumb/SingleThumb.tsx
src/components/RangeSlider/components/SingleThumb/index.ts
src/components/RangeSlider/components/index.ts
src/components/RangeSlider/index.ts
src/components/RangeSlider/types.ts
src/components/index.ts
types/src/components/index.d.ts

Basic Slider Component Implementation is done, same component will be used in numeric facet widget

fix: id:46102 Slider Range Components

---

src/components/TextField/TextField.scss
themes/Delicious/TextField.scss

Apply ellipses to label in mobile devices

fix: id:45995 label ellipses issue in mobile devices

---

src/components/Table/Table.scss

Make alignment of table Data in responsive view

fix: id:45992 table data alignment in mobile view

---

src/components/Badge/Badge.tsx
src/components/Button/Button.tsx
src/components/Dropdown/Dropdown.tsx
src/components/Dropdown/DropdownItem.tsx
src/components/Heading/Heading.tsx
src/components/Picker/Picker.tsx
src/components/Popover/Popover.tsx
src/components/SideNavigation/SideNavigation.tsx
src/components/Table/Table.tsx
src/components/Table/TableHead.tsx
src/components/Table/interface.ts
src/components/TextField/TextField.tsx
src/components/TreeView/TreeView.tsx

https://atera.tpondemand.com/entity/46739-fe-need-to-add-id-property

feat: 46739 added ID properties for automation script

---

src/components/Pagination/Pagination.scss
src/components/Pagination/Pagination.tsx

Pagination broken in meaasgeDef

fix: id:47045 Pagination broken in meaasgeDef

---

src/components/Calendar/Calendar.css

apply  calendar to match with default theme

fix: id:42679 apply calendar to match with default theme

---

src/components/Picker/Picker.scss

FE - MessageDef - Recipient filter - UI issue when suggestion list is more

fix: id:47493 recipient filter - ui issue when suggestion list is more

---

src/components/Drawer/Drawer.scss

hide vertical and horizontal scrollbar from windows screen

fix: id:44592 hide vertical and horizontal scrollbar from windows screen

---

example/src/App.tsx
src/components/AppBar/AppBar.scss
src/components/AppBar/AppBar.tsx
src/components/Button/Button.scss
src/components/Login/Login.scss
src/components/TextField/TextField.scss
src/components/TextField/TextField.tsx

fix: id:47681 top bar shrink

---

src/components/Pagination/PageSize.tsx
src/components/Pagination/Pagination.scss

item per page button animation issue

fix: id:48202 item per page animation issue

---

src/components/Tab/Tab.scss
src/components/Tab/Tab.tsx
src/components/Tab/TabPanel.tsx
src/styles/foundation/colors.scss

Tab component HTML structure change

fix: id:48167 Tab component HTML structure change

---

src/components/FlexBox/FlexBox.tsx

changes for default flext wrap property

fix: id:48427 changes for default flext wrap property

---

src/components/FlexBox/FlexBox.tsx

Revert "fix: id:48427 changes for default flext wrap property"

---

src/components/Drawer/Drawer.scss

drawer scroller styling change

fix: id:47832 drawer scroller style change

---

src/components/Icon/Icon.tsx

Co-authored-by: SADAF ADREES <freelancer.sadaf@gmail.com>

fix: id:48337 icon adding minusMinor (#603)

---

src/components/SwitchCheckbox/SwitchCheckbox.scss

Switch on/off color change

---

src/components/Pagination/PageSize.tsx
src/components/Pagination/Pagination.scss

item per page alignment issue resolve in SVSU

fix: id:48202 item per page alignment issue resolve in SVSU

---

src/components/Icon/Icon.tsx
src/components/TreeView/TreeView.scss
src/components/TreeView/TreeView.tsx

TreeView component Accessibility

fix: id:0084 TreeView component Accessibility

---

src/components/Pagination/Pagination.scss

pagination next/prev button alignment

fix: id:50162 pagination next/prev button alignment

---

src/components/Pagination/Pagination.scss

Alignment issue due to blank list in pagination

fix: id:50353 Alignment issue due to blank list in pagination

---

src/components/Table/RowAction.tsx

add visually hidden component in table more action button

fix: id:46394 add visually hidden component in table more action button

---

src/components/SwitchCheckbox/SwitchCheckbox.scss

Base color use for switch button

Base color use for switch button

---

example/src/App.tsx
src/components/ComboBox/ComboBox.tsx
src/components/ComboBox/ComboBoxItem.tsx
src/components/PopoverPicker/PopoverPicker.tsx

Correct the spelling from Tabuler to Tabular

fix: id:50456 Correct the spelling from Tabuler to Tabular

---

package-lock.json
package.json
src/components/PopoverPicker/PopoverPicker.tsx

match popover width with figma design

fix: match popover width with figma design

---

src/components/Picker/Picker.scss
src/components/PopoverPicker/PopoverPicker.scss

fix overlapping issue with other components

fix overlapping issue with other components

---

src/components/ChoiceList/ChoiceList.scss

Message Channel message/delivery option alignment issue

fix: id:50393 Message Channel message/delivery option alignment issue

---

src/components/Table/Table.scss

more action button color change on keyboard focus

fix: id:50494 more action button color change on keyboard focus

---

src/components/Dropdown/Dropdown.scss
src/components/Dropdown/DropdownItem.tsx

add button component in dropdown and make style changes

fix: id:50549 add button component in dropdown and make style changes

---

example/src/App.tsx
src/components/BodyText/BodyText.scss
src/components/BodyText/BodyText.tsx
src/components/BodyText/index.ts
src/components/BodyText/test/BodyText.test.tsx
src/components/MultipleCheckboxFacets/MultipleCheckboxFacets.tsx
src/components/ThemeIdentifiers.ts
src/components/index.ts
src/styles/foundation/colors.scss
src/styles/shared.scss
src/styles/shared/colors.scss

bodytext component in next branch

fix: id:50594 create bodytext component in next branch

---

src/components/SwitchCheckbox/SwitchCheckbox.scss

switch component accessibility

fix: id:50733 switch component accessibility

---

src/components/Choice/Choice.scss
src/components/Dropdown/Dropdown.scss
src/components/Picker/Picker.tsx
src/components/TextField/TextField.tsx

add z index to choice component for work in dropdown

fix: id:50707 add z index to choice component for work in dropdown

---

src/components/Picker/Picker.tsx
src/components/Table/Table.scss
src/components/Table/Table.tsx
src/components/TextField/TextField.tsx

add scroller if colum is more in table

fix: id:45762 add scroller if colum is more in table

---

src/components/Login/Login.tsx
src/components/Modal/Modal.tsx
src/components/Picker/Picker.tsx
src/components/TextField/TextField.scss
src/components/TextField/TextField.tsx
src/components/ToggleButtonGroup/ToggleButtonGroup.tsx
themes/Delicious/Select.scss
themes/Delicious/TextField.scss

fix: id:51815 wave tool error issue solving

---

src/components/Button/Button.scss
src/components/Dropdown/Dropdown.scss
src/components/Dropdown/DropdownItem.tsx
src/components/Login/Login.scss

sign out clickable area
- add full width to dropdown button
- apply display block to signout anchor
- apply css property to full width button

fix: id:50798 sign out clickable area

---

src/components/Accordion/Accordion.scss
src/components/Accordion/AccordionItem.tsx
src/components/SideNavigation/SideNavigation.scss
src/components/SideNavigation/SideNavigation.tsx

create new style and correction in existing style

fix: id:51961 create new style and correction in existing style

---

src/components/SideNavigation/SideNavigation.tsx

reduce the width of side navigation

fix: id:51961 reduce the width of side navigation

---

src/components/SideNavigation/SideNavigation.tsx

set alignment of accordion heading if no child

fix: id:51961 set alignment of accordion heading if no child

---

src/components/ComboBox/ComboBox.tsx
src/components/Login/Login.scss

Sign out button clickable area add margin and padding to anchor

fix: id:50798 Sign out button clickable area

---

src/components/SideNavigation/SideNavigation.scss
src/components/SideNavigation/SideNavigation.tsx

Arrow alignment if accordion has no child side navigation

fix: id:52031 Arrow alignment if accordion has no child side navigation

---

src/components/Chip/Chip.scss

MessageDef search dropdown icon alignment

fix: id:51905 MessageDef search dropdown icon alignment

---

src/components/Accordion/Accordion.scss
src/components/SideNavigation/SideNavigation.scss

accordian body overlapping with header

fix: id:52023 accordian body overlapping with header

---

src/components/BodyText/BodyText.tsx
src/components/BodyText/tests/BodyText.test.tsx

Added componentClass and adding componentStyle in props.
Extended tags with div tag

US:52801: BodyText Component Updates

---

src/components/Button/Button.scss
src/components/Picker/Picker.tsx

checkbox width issue resolve in full width button

fix: id:50707 checkbox width issue resolve in fullwidth button

---

src/components/Dropdown/Dropdown.scss
src/components/SideNavigation/SideNavigation.tsx

More action option styling in app list tree view

fix: id:52069 More action option styling in app list tree view

---

src/components/Button/Button.scss
src/components/Picker/Picker.tsx

Show delete checkbox width issue

fix: id:50707 Show delete checkbox width issue

---

src/components/Picker/Picker.tsx
src/components/TextField/TextField.scss
themes/Delicious/TextField.scss

fix: id:52033 Error border to text area

---

src/components/Pagination/PageSize.tsx
src/components/Pagination/Pager.tsx

Item per page code correction in pagination

fix: id:50756 Item per page code correction in pagination

---

src/components/RangeSlider/components/DualThumb/DualThumb.scss
src/components/RangeSlider/components/DualThumb/DualThumb.tsx
src/components/RangeSlider/components/DualThumb/RangeSlider.scss

fix: id:48341 Range slider styling

---

src/components/SideNavigation/SideNavigation.scss
src/components/SideNavigation/SideNavigation.tsx

set hover and focus changes in side navigation

fix: id:52620 set hover and focus changes in side navigation

---

themes/Delicious/TextField.scss

text field height issue when text enter

fix: id:52636 text field height issue when text enter

---

src/components/Picker/LazyPicker.tsx
src/components/Picker/Picker.tsx
src/components/SideNavigation/SideNavigation.scss

focus effect on main heading of sidebar

fix: id:52620 focus effect on main heading of sidebar

---

src/components/Table/Table.scss

remove after from desktop and add in mobile in table tr

fix: id:52800 remove after from desktop and add in mobile in table tr

---

src/components/Picker/Picker.scss

Dropdown width issue resolve in picker with more button

fix: id:52463 Dropdown width issue resolve in picker with more button

---

src/components/Calendar/Calendar.css

calendar component accessibility

fix: id:47815 calendar component accesibility

---

src/components/Chip/Chip.scss

UI issue resolve when subscriber name is long

fix: id:52913 UI issue resolve when subscriber name is long

---

src/components/Modal/Modal.scss

Set styling of table and width of modal in small

fix: id:52639 Set styling of table and width of modal in small

---

src/components/Picker/Picker.scss

add spacing below the subscirber chip

fix: id:52913 add spacing below the subscirber chip

---

src/components/List/List.scss

remove font weight from devider styling in list

fix: id:52979 remove font weight from devider styling in list

---

src/components/List/List.scss

remove font weight to span childs

fix: id:52979 remove font weight to span childs

---

src/components/Picker/Picker.scss

Changes in width on picker component popover

fix: id:53157 changes in width on picker component popover

---

src/components/Picker/Picker.scss

dropdown issue resolve in message recipient picker dropdown

fix: id:53157 dropdown issue resolve in message recipient picker dropdown

---

src/components/TextField/TextField.scss

Text area content overlap with its label text

fix: id:53325 Text area content overlap with its label text

---

src/components/Picker/Picker.scss

fix: id:53445 Narrow result styling issue

---

src/components/Choice/Choice.scss

changes in style when user click beside the choice text

fix: id:53486 changes in style when user click beside the choice text

---

azure-pipelines-trigger.yml

added trigger: none in yaml file as pushes to engage-ui are triggering build

added trigger none

---

example/src/index.html
example/src/index.tsx
src/components/Modal/Modal.scss
src/components/Modal/Modal.tsx

fix: id:53575 Printable modal content

---

src/components/Checkbox/Checkbox.tsx
src/components/Modal/Modal.tsx

Revert "fix: id:53486 checkbox component changes for label click function"

---

src/components/Modal/Modal.scss

add scale in body to reduce hide content

fix: id:53575 add scale in body to reduce hide content

---

src/components/Modal/Modal.scss

remove scale property from scale media query

fix: id:53756 remove scale property from scale media query

---

src/components/BodyText/BodyText.tsx

span element added to BodyText component

fix: id:53962 span element added to BodyText component

---

src/components/Login/Login.tsx

popover alignment in login profile click

fix: id:53621 popover alignment in login profile click

---

src/components/AppBar/AppBar.tsx
src/components/Choice/Choice.scss

remove margin bottom from label checkbox component

fix: id:54042 remove margin bottom from label checkbox component

---

src/components/TextField/TextField.tsx

fix: id:54164 textfield props correction

---

src/components/AppBar/AppBar.tsx
src/components/Picker/Picker.scss

53157 ui issue resolve in header dropdown picker component

fix: id:53157 ui issue resolve in header dropdown picker component

---

example/src/App.tsx
src/components/Tooltip/Tooltip.scss
src/components/Tooltip/Tooltip.tsx
src/components/Tooltip/TooltipOverlay.tsx

Help text and tool tip for search

fix: id:53855 Help text and tool tip for search

---

src/components/Table/Table.scss

description width issue when max character apply in table

fix: id:54307 description width issue when max character apply in table

---

src/components/Table/Table.scss

UI correction in contentDef selection

fix: id:54323 UI correction in contentDef selection

---

example/src/App.tsx
src/components/SwitchCheckboxIcon/SwitchCheckboxIcon.scss
src/components/SwitchCheckboxIcon/SwitchCheckboxIcon.tsx
src/components/SwitchCheckboxIcon/index.tsx
src/components/index.ts

New Switch component styling creation

fix: id:54321 New Switch component styling creation

---

src/components/Picker/Picker.scss
src/components/Picker/Picker.tsx

relationship widget tabular view styling correction

fix: id:53157 relationship widget tabular view styling correction

---

src/components/Picker/Picker.tsx

condition correction in picker component

fix: condition correction in picker component

---

src/components/Chip/Chip.scss

hover styling correction in chip component

fix: id:53705 hover styling correction in chip component

---

src/components/Select/Select.scss
src/components/Select/Select.tsx
src/components/TextField/TextField.tsx

prefix in text field and select in read only

fix: id:54386,54352 prefix in text field and select in read only

---

src/components/Table/RowAction.tsx
src/components/Table/Table.tsx

More action alignment with long description in table

fix: id:54448 More action alignment with long description in table

---

src/components/TextField/TextField.scss
src/components/TextField/TextField.tsx

Number field button click select text

fix: id:54474 Number field button click select text

---

example/src/App.tsx
src/components/AppBar/AppBar.tsx
src/components/NoData/NoData.scss
src/components/NoData/NoData.tsx
src/components/NoData/index.ts
src/components/ThemeIdentifiers.ts
src/components/index.ts

feat: id:54138 No data component creation

---

src/components/Button/Button.tsx

title prop added in button component

fix: id:54625 title prop added in button component

---

src/components/Table/RowAction.tsx

more action popover scroller remove

fix: id:54675 more action popover scroller remove

---

themes/Delicious/Select.scss
themes/Delicious/TextField.scss

color changes to label for read and edit format

fix: id:54700 color changes to label for read and edit format

---

src/components/Table/RowAction.tsx

content item  button popover alignment in small screen

fix: id:54617 content item  button popover alignment in small screen

---

src/components/Login/Login.tsx

remove visuallyhidden and  add title in login component

fix: id:54606 remove visuallyhidden and  add title in login component

---

src/components/Button/Button.tsx
src/components/NoData/NoData.tsx
src/components/Table/Table.tsx

Add hidden text in more action colum header in table

fix: id:54614 Add hidden text in more action colum header in table

---

src/components/Tab/Tab.tsx

fix: id:54625 add title props in tab

---

src/components/Drawer/DrawerContent.tsx
src/components/Modal/Modal.tsx

add title props in drawer and modal close button

fix: id:5625 add title props in drawer and modal close button

---

src/components/Tooltip/Tooltip.tsx

wave tool error solving for tooltip component

fix: id:55006 wave tool error solving for tooltip component

---

src/components/ComboBox/ComboBox.tsx

remove static width from combobox popover

fix: id:54984 remove static width from combobox popover

---

src/components/ComboBox/ComboBox.tsx

change height of popover hen screen height is less

fix: id:54975 change height of popover hen screen height is less

---

src/components/ComboBox/ComboBox.tsx

add backdrophidden prop in combobox component

fix: id:54974 add backdrophidden prop in combobox component

---

src/components/TextField/TextField.tsx

autosuggestion off error solving

fix: id:55116 autosuggestion off error solving

---

src/components/Banner/Banner.scss
src/components/Banner/Banner.tsx
src/styles/foundation/colors.scss
themes/Delicious/Banner.scss
themes/Delicious/index.tsx

fix: id:55035 banner icon color correction

---

src/styles/foundation/colors.scss

fix: id:55112 change mid text color

---

src/components/Table/Table.scss

long description name warped in table

fix: id:55538 long description name warped in table

---

src/components/SwitchCheckbox/SwitchCheckbox.scss

text color change in disable switch box

fix: id:55584 text color change in disable switch box

---

src/components/SwitchCheckbox/SwitchCheckbox.tsx

add label text in input type in switchbox

fix: id:55606 add label text in input type in switchbox

---

src/components/SwitchCheckbox/SwitchCheckbox.scss

icon text alignment correction

fix: id:55584 icon text alignment correction

---

src/components/Banner/Banner.scss
themes/Delicious/Banner.scss
themes/Delicious/foundation/border-radius.scss
themes/Delicious/index.tsx

code corrections in UI component and delicious theme

fix: code corrections in ui component and delicious theme

---

src/components/Picker/Picker.scss
src/components/Picker/Picker.tsx

fix: id:55646 all subscription icon styling

---

src/components/Banner/Banner.tsx
src/components/Picker/AutoSuggestText.tsx
src/components/Picker/Picker.tsx

change element type in banner sub text

fix: id:55501 change element type in banner sub text

---

src/components/MultipleCheckboxFacets/MultipleCheckboxFacets.tsx

change option count color in facet component

fix: id:55109 change option count color in facet component

---

src/components/RangeSlider/components/DualThumb/DualThumb.scss
src/components/RangeSlider/components/DualThumb/DualThumb.tsx

range slider styling corrections

fix: id:55718 range slider styling corrections

---

src/components/ComboBox/ComboBox.scss

selection display on long press on up/down arrow combobox

fix: id:55604 selection display on long press on up/down arrow combobox

---

src/components/TextField/TextField.scss

placeholder color change in textfield component

fix: id:55109 placeholder color change in textfield component

---

src/components/Segment/Segment.scss

hover/focus styling change in segment component

fix: id:55692 hover/focus styling change in segment component

---

src/components/Segment/Segment.scss

spacing creation in segemnt button

fix: id:55692 spacing creation in segemnt button

---

example/src/App.tsx
src/components/Tab/Tab.scss
src/components/Tab/TabPanel.tsx
src/components/Table/BannerRow.tsx

fix: id:55842 create vertical view of tab

---

src/components/Tab/Tab.scss

fix: id:55842 border corner corrections

---

src/components/Tab/Tab.scss

tab vertical styling corrections

fix: id:55841 vertical tab styling correction

---

src/components/Table/BannerRow.tsx

Revert "fix-combobox"

---

example/src/App.tsx
src/components/Tab/Tab.tsx

bugfix/55842_add_title_prop_in_tab

fix: id:55842 add title prop in tab

---

src/components/Tab/Tab.scss

add relative to vertical class

add relative to vertical class

---

example/src/App.tsx
src/components/Tab/Tab.scss

fix: id:55842 color changes in button icons

---

src/components/Process/Process.scss

remove padding from process ul

fix: id:55841 remove padding from process ul

---

example/src/App.tsx
src/components/Tab/Tab.tsx

fix: id:55842 add tooltip to tab component

---

example/src/App.tsx

create example for column responsive

create example for column responsive

---

src/components/BreadCrumb/BreadCrumb.scss
src/components/Button/Button.scss
src/components/ButtonGroup/ButtonGroup.scss
src/components/Chip/Chip.scss
src/components/ComboBox/ComboBox.scss
src/components/Connected/Connected.scss
src/components/MaskTextField/MaskTextField.scss
src/components/MultipleCheckboxFacets/MultipleCheckboxFacets.scss
src/components/PopoverPicker/PopoverPicker.scss
src/components/SideNavigation/SideNavigation.scss
src/components/Tab/Tab.scss
src/components/TextField/TextField.scss
src/components/ToggleButtonGroup/ToggleButtonGroup.scss

correction in unit after changes

fix: id:56037 correction in unit after changes

---

example/src/App.tsx
src/components/MyDropzone/MyDropzone.tsx
src/components/Process/Process.scss
src/components/Process/Process.tsx

add icon prop in process component

fix: add icon prop in process component

---

src/components/Popover/PopoverOverlay.tsx
src/components/PositionedOverlay/PositionedOverlay.tsx
src/components/Table/Table.tsx

Revert "fix: remove console"

---

src/components/Table/Table.tsx

This reverts commit 5af096e558714a6b455d259960d6c9bc2635942d, reversing changes made to e49110e0a03fe5a423961cf3a3a6c901a477b237.

Revert "Merge pull request #1184 from emgage/bug63794"
